<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>Project Management tool console app. To work on multiple projects at once.</description>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>PMT Console</label>
    <navType>Console</navType>
    <tabs>inov8__PMT_Home</tabs>
    <tabs>inov8__PMT_Project__c</tabs>
    <tabs>inov8__PMT_Program__c</tabs>
    <tabs>standard-Case</tabs>
    <tabs>inov8__PMT_Phase__c</tabs>
    <tabs>inov8__PMT_Task__c</tabs>
    <tabs>inov8__Resource_Management</tabs>
    <tabs>inov8__PMT_Resource_Availability__c</tabs>
    <tabs>inov8__PMT_Resource_Allocation__c</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-Feed</tabs>
    <tabs>standard-ProcessInstanceWorkitem</tabs>
    <tabs>inov8__PMT_Error_Log__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>inov8__PMT_Console_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>inov8__PMT_Error_Log__c</tab>
        </mappings>
        <mappings>
            <tab>inov8__PMT_Home</tab>
        </mappings>
        <mappings>
            <fieldName>inov8__Project__c</fieldName>
            <tab>inov8__PMT_Phase__c</tab>
        </mappings>
        <mappings>
            <tab>inov8__PMT_Program__c</tab>
        </mappings>
        <mappings>
            <tab>inov8__PMT_Project__c</tab>
        </mappings>
        <mappings>
            <fieldName>inov8__Resource_Availability__c</fieldName>
            <tab>inov8__PMT_Resource_Allocation__c</tab>
        </mappings>
        <mappings>
            <tab>inov8__PMT_Resource_Availability__c</tab>
        </mappings>
        <mappings>
            <fieldName>inov8__Phase__c</fieldName>
            <tab>inov8__PMT_Task__c</tab>
        </mappings>
        <mappings>
            <tab>inov8__Resource_Management</tab>
        </mappings>
        <mappings>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <tab>standard-Dashboard</tab>
        </mappings>
        <mappings>
            <tab>standard-Feed</tab>
        </mappings>
        <mappings>
            <tab>standard-ProcessInstanceWorkitem</tab>
        </mappings>
        <mappings>
            <tab>standard-report</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
